version: "3"

networks:
  vocalvibe-network:
    driver: bridge
    name: vocalvibe-network


services:
  db:
    image: ankane/pgvector # Used this considering future usecases for vector databases
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      vocalvibe-network:
        aliases: [postgres]
    volumes:
      - ../../.devcontainer/data/:/docker-entrypoint-initdb.d/